name: Deploy

on:
  watch:
    types: [started]
    
env:
  KODI_VERSION: 17.6

jobs:
  container-build:
    runs-on: ubuntu-18.04
    container: cyrus0w/build-kodi-krypton
    steps:
    - name: Checkout xbmc${KODI_VERSION} code
      uses: actions/checkout@v3
      with:
        repository: xbmc/xbmc
        ref: ${KODI_VERSION}-Krypton
        path: kodi-android
    - name: Build kodi dependent
      continue-on-error: true
      run: |
        cd kodi-android/tools/depends
        ./bootstrap
        sudo ./configure --with-tarballs=/opt/xbmc-tarballs --host=arm-linux-androideabi --with-sdk-path=/opt/android-sdk-linux --with-ndk=/opt/android-ndk-r12b --with-toolchain=/opt/arm-linux-androideabi-4.9-vanilla/android-21 --prefix=/opt/xbmc-depends
        sudo make -j$(getconf _NPROCESSORS_ONLN) | tee build.log 2>&1
        sudo make -C target/binary-addons ADDONS="pvr.iptvsimple inputstream.rtmp audioencoder.flac audioencoder.wav"
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name: Build kodi
      continue-on-error: true
      run: |
        cd ../../kodi-android
        sudo make -C tools/depends/target/xbmc
        sudo make
        sudo make apk
        sudo mkdir -p /opt/images/
        sudo mv -f *.apk /opt/packages/
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/packages
