name: Deploy

on:
  watch:
    types: [started]
    
env:
  REPO_URL: https://github.com/xbmc/xbmc.git
  REPO_BRANCH: 17.6-Krypton
  MY_REPO_URL: https://github.com/cyrus0w/build-kodi-Krypton.git
  DIY_BASH: diy.sh

jobs:
  container-build:
    runs-on: ubuntu-18.04
    container: ubuntu:16.04
    steps:
    - name: System basic environment settings
      run: |
        apt-get update
        apt-get install build-essential default-jdk git curl wget autoconf unzip zip zlib1g-dev gawk gperf cmake openjdk-8-jdk -y
        apt-get install lib32stdc++6 lib32z1 lib32z1-dev -y
        apt-get install libssl-dev libcurl4-openssl-dev qt4-qmake libvorbis-dev libncurses5-dev libsqlite3-dev libgdbm-dev libreadline-dev libbz2-dev tk8.6-dev libdb-dev python-dev libncurses-dev tcl8.6-dev sqlite3 -y
    - name: Android compilation environment settings
      run: |
        wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
        tar -zxf android-sdk_r24.4.1-linux.tgz -C /opt
        wget -c https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
        unzip android-ndk-r12b-linux-x86_64.zip -d /opt
        cd /opt/android-sdk-linux/tools
        echo yes|./android update sdk -u -t platform,platform-tool
        echo yes|./android update sdk --all -u -t build-tools-20.0.0
        cd /opt/android-ndk-r12b/build/tools
        ./make-standalone-toolchain.sh --ndk-dir=../../ --install-dir=/opt/arm-linux-androideabi-4.9-vanilla/android-21 --platform=android-21 --toolchain=arm-linux-androideabi-4.9
        keytool -genkey -keystore ~/.android/debug.keystore -v -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" -keypass android -storepass android -keyalg RSA -keysize 2048 -validity 10000
    - name: Checkout
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git clone ${{ env.MY_REPO_URL }} build-kodi
    - name: Checkout xbmc code
      run: |
        git clone -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} kodi-android
    - name: Custom settings
      run: |
        [ -f build-kodi/diy-kodi-krypton/${{ env.DIY_BASH }} ] && chmod +x build-kodi/diy-kodi-krypton/${{ env.DIY_BASH }}; \
        $GITHUB_WORKSPACE/build-kodi/diy-kodi-krypton/${{ env.DIY_BASH }}
    - name: Build kodi dependent
      run: |
        ls
        pwd
        cd $GITHUB_WORKSPACE/kodi-android/tools/depends
        ./bootstrap
        ./configure --with-tarballs=/opt/xbmc-tarballs --host=arm-linux-androideabi --with-sdk-path=/opt/android-sdk-linux --with-ndk=/opt/android-ndk-r12b --with-toolchain=/opt/arm-linux-androideabi-4.9-vanilla/android-21 --prefix=/opt/xbmc-depends
        make -j$(getconf _NPROCESSORS_ONLN) | tee build.log 2>&1
        make -C target/binary-addons ADDONS="pvr.iptvsimple inputstream.rtmp audioencoder.flac audioencoder.wav"
    - name: Build kodi
      run: |
        pwd
        cd $GITHUB_WORKSPACE/kodi-android
        make -C tools/depends/target/xbmc
        sudo make
        make apk
        mkdir -p /opt/images/
        mv -f *.apk /opt/packages/
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/packages
