name: Deploy

on:
  watch:
    types: [started]
    
env:
  KODI_VERSION: 17.6

jobs:
  container-build:
    runs-on: ubuntu-18.04
    container: ubuntu:16.04
    steps:
    - name: System basic environment settings
      run: |
        apt-get update
        apt-get install build-essential default-jdk git curl wget autoconf unzip zip zlib1g-dev gawk gperf cmake openjdk-8-jdk -y
        apt-get install lib32stdc++6 lib32z1 lib32z1-dev -y
        apt-get install libssl-dev libcurl4-openssl-dev qt4-qmake libvorbis-dev libncurses5-dev libsqlite3-dev libgdbm-dev libreadline-dev libbz2-dev tk8.6-dev libdb-dev python-dev libncurses-dev tcl8.6-dev sqlite3 -y
    - name: Android compilation environment settings
      run: |
        wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
        tar -zxf android-sdk_r24.4.1-linux.tgz -C /opt
        wget -c https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
        unzip android-ndk-r12b-linux-x86_64.zip -d /opt
        cd /opt/android-sdk-linux/tools
        echo yes|./android update sdk -u -t platform,platform-tool
        echo yes|./android update sdk --all -u -t build-tools-20.0.0
        cd /opt/android-ndk-r12b/build/tools
        ./make-standalone-toolchain.sh --ndk-dir=../../ --install-dir=/opt/arm-linux-androideabi-4.9-vanilla/android-21 --platform=android-21 --toolchain=arm-linux-androideabi-4.9
        keytool -genkey -keystore ~/.android/debug.keystore -v -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" -keypass android -storepass android -keyalg RSA -keysize 2048 -validity 10000
    - name: Checkout xbmc code
      run: |
        cd ~
        git clone https://github.com/xbmc/xbmc
    - name: Build kodi dependent
      continue-on-error: true
      run: |
        cat /etc/os-release
        ls
        pwd
        cd kodi-android/tools/depends
        ./bootstrap
        sudo ./configure --with-tarballs=/opt/xbmc-tarballs --host=arm-linux-androideabi --with-sdk-path=/opt/android-sdk-linux --with-ndk=/opt/android-ndk-r12b --with-toolchain=/opt/arm-linux-androideabi-4.9-vanilla/android-21 --prefix=/opt/xbmc-depends
        sudo make -j$(getconf _NPROCESSORS_ONLN) | tee build.log 2>&1
        sudo make -C target/binary-addons ADDONS="pvr.iptvsimple inputstream.rtmp audioencoder.flac audioencoder.wav"
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name: Build kodi
      continue-on-error: true
      run: |
        cd ../../kodi-android
        sudo make -C tools/depends/target/xbmc
        sudo make
        sudo make apk
        sudo mkdir -p /opt/images/
        sudo mv -f *.apk /opt/packages/
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/packages
