name: Deploy

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: System basic environment settings
      run: |
        sudo apt-get install build-essential default-jdk git curl autoconf unzip zip zlib1g-dev gawk gperf cmake -y
        sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev apt-get -y
        sudo apt-get install libssl-dev libcurl4-openssl-dev qt4-qmake libvorbis-dev libncurses5-dev libsqlite3-dev libgdbm-dev libreadline-dev libbz2-dev tk8.6-dev libdb-dev python-dev libncurses-dev tcl8.6-dev sqlite3 -y
    - name: Setup Java JDK
      uses: actions/setup-java@v3.4.1
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Android develp tools settings
      run: |
        pwd
        wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
        tar -zxf android-sdk_r24.4.1-linux.tgz
        wget -c https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
        unzip android-ndk-r12b-linux-x86_64.zip
        cd android-sdk-linux/tools
        ./android update sdk -u -t platform,platform-tool
        ./android update sdk --all -u -t build-tools-20.0.0
        cd ../android-ndk-r12b/build/tools
        ./make-standalone-toolchain.sh --ndk-dir=../../ --install-dir=~/arm-linux-androideabi-4.9-vanilla/android-21 --platform=android-21 --toolchain=arm-linux-androideabi-4.9
        keytool -genkey -keystore ~/.android/debug.keystore -v -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" -keypass android -storepass android -keyalg RSA -keysize 2048 -validity 10000
    - name: Checkout xbmc17.6 code
      uses: actions/checkout@v3
      with:
        repository: xbmc/xbmc
        ref: 17.6-Krypton
    - name: Build kodi dependent
      run: |
        cd $HOME/kodi-android/tools/depends
        ./bootstrap
        ./configure --with-tarballs=~/xbmc-tarballs --host=arm-linux-androideabi --with-sdk-path=~/android-sdk-linux --with-ndk=~/android-ndk-r12b --with-toolchain=~/arm-linux-androideabi-4.9-vanilla/android-21 --prefix=~/xbmc-depends
        make -j$(getconf _NPROCESSORS_ONLN)
        make -C target/binary-addons ADDONS="pvr.iptvsimple inputstream.rtmp audioencoder.flac audioencoder.wav"
    - name: Build kodi
      run: |
        cd $HOME/kodi-android
        make -C tools/depends/target/xbmc
        make
        make apk
        sudo mkdir -p /opt/images/
        sudo mv -f *.apk /opt/packages/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/packages
